name = "christmas-message-api"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "beans_db"
database_name = "beans-db"
database_id = "fb07bdcd-412a-4db5-bfc7-eadc8d84bfdb"

[observability]

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
